clean:
	@rm -rf ./dist/*
	@rm -rf ./content/posts/who-are-we.md

build:
	@hugo -d dist

post:
	@hugo new posts/who-are-we.md
	@chmod u+x ./content/posts/who-are-we.md
	@hugo new posts/nMJj2Ppm.md
	@chmod u+x ./content/posts/nMJj2Ppm.md
	@hugo new posts/T25Gq4St.md
	@chmod u+x ./content/posts/T25Gq4St.md
	@hugo new posts/3hzZ08iK.md
	@chmod u+x ./content/posts/3hzZ08iK.md
	@hugo new posts/tW9I3TQi.md
	@chmod u+x ./content/posts/tW9I3TQi.md

