build:
	@hugo -d dist

post:
        @hugo new posts/who-are-we.md
        @chmod u+x ./content/posts/who-are-we.md
        @hugo new posts/nMJj2Ppm.md
        @chmod u+x ./content/posts/nMJj2Ppm.md

clean:
	@rm -rf ./dist/*
	@rm -rf ./content/posts/who-are-we.md
